.travis.yml
#90
kqueue works fine, so I didn't add it for now.
It may be worth adding GODEBUG=cgocheck=2 too? Much like using -race in tests.
=> Run Travis against Go 1.6

node.go
This PR is originally by mnagel to zillode/notify:
> I use Syncthing to recursively watch my whole `$HOME`.
> It fails on the FUSE mount `.gvfs` and this took me *muuuch* to long to figure out.
> With this change it is much more easy to debug such issues.
=> include node name in error when traversing fails

event.go, event_inotify.go, example_inotify_test.go, sync_unix_test.go, watcher_inotify.go
Implement it with by calling epoll_pwait(). According to man epoll_pwait,
calling epoll_pwait with sigmask of NULL is identical to
epoll_wait.
Bring the fixes from golang.org/x/sys/unix to support these
transparently on arm64.
This is needed to fix https://github.com/minio/mc/issues/2047
=> epoll_wait syscall doesn't exist on arm64.

README.md, doc.go, event_readdcw.go
This is the result of the discussions in #117.
It adds some information about how events work for readdcw (difference between filters and actions). Additionally there is a sentence in the "main documentation" refering to the events_*.go files for information about available events and very few typo/language errors I came across (I hope I didn't add any myself).
Edit: And add syncthing-inotify to the programs using notify.
=> Improve documentation (comments) about events and polish

watcher_inotify.go
The InotifyInit syscall doesn't exist on all architectures, but
InotifyInit1 does.  In the kernel implementation, inotify_init is just a
wrapper around inotify_init1 and passes in zero for the only parameter
which is a flags field.
=> Switch to InotifyInit1 syscall for mips64/etc

debug.go, debug_nodebug.go, watcher_test.go
Now you can enable debugging both by debug tag and setting an environment variable. Also the output includes timestamps, which is potentially crucial to debug event based problems.
=> Use log package for timestamps and enable debugging via env var NOTIFY_DEBUG

node.go
Missing nodes are already reported as `os.PathError`. This does the same for the error returned when setting up a recursive watch with a non-recursive watcher, i.e. during traversing. The error string is the same as before, so user of this library wont notice the change. This allows to check the underlying error and which path causes the problem. An example of a use case is for Syncthing, where we want to notify the user when the error is due to hitting the inotify handler limit.
=> node: Return traverse error as os.PathError

watcher_fsevents_cgo.go, watcher_fsevents_go1.10.go, watcher_fsevents_go1.9.go
The Core Services reference types became integer shaped after being
pointer shaped in Go 1.9. I moved the thing out into a constant zero or
nil variable according to the Go version, in order to avoid duplicating
a bunch of code into separate files.
This is the required fix according to
https://go-review.googlesource.com/c/go/+/66332.
This passes tests with Go 1.9.2. and 1.10beta1.
=> Handle pointers that are now integers in Go 1.10 (fixes #135)

watcher_fsevents_cgo.go
According to https://github.com/rjeczalik/notify/pull/140#issuecomment-354991635 the call to sleep was added for debugging.
=> FSEvents: remove time.Sleep call in run loop setup

.travis.yml
Running against tip in order to allow for noticing any breaking
changes with upcomming Go release.
=> travis: run against tip

debug_debug.go, debug_nodebug.go, watcher_readdcw.go
The `Unwatch` method on Windows is asynchronous. Thus, when calling `Watch`, `Unwatch` and `Watch` on the same path, the `Unwatch` state may happen after the second `Watch` call. This means that second `Watch` will be skipped as already created.
This commit makes second `Watch` call invalidate `Unwatch` state. So `Watch->Unwatch->Watch` calls will be basically a no-op. This doesn't solve all the problems since the second `Watch` might have different events to handle. However, the implementation should use `Rewatch` method instead.
Also, the code fixes a data race that may occur when invalidating grip handle.
Fixes: #150 
/cc @calmh 
<details>
<summary>Environment and tests</summary>
```
C:\Users\ppknap\go\src\github.com\rjeczalik\notify (issue150 -> origin)
λ ver
Microsoft Windows …
```
=> readdcw: close handle during unwatch state

watcher_notimplemented.go, watcher_stub.go, watcher_trigger.go
Instead of panicking, return a stub watcher that returns a sensible error message like the "not implemented" one does.
Another approach was implemented by @calmh, in that the watcher isn't initialized initially but only on first use and the initialization function recovers from panics: https://github.com/syncthing/notify/commit/2556ab349002cb2f9c250783c06b1976fc7d23b4
=> kqueue: Don't panic when an error occurs on init (fixes #149)

watcher_fsevents_cgo.go
Since using notify in Syncthing the following panic occurs randomly (see syncthing/syncthing#4854):
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x417b012]
goroutine 19 [running, locked to thread]:
github.com/syncthing/syncthing/vendor/github.com/syncthing/notify.gostream(0x6b00c30, 0x4, 0x11, 0x6900ef0, 0x4df9000, 0x4df8000)
/Users/jb/src/github.com/syncthing/syncthing/vendor/github.com/syncthing/notify/watcher_fsevents_cgo.go:107 +0x2d2
github.com/syncthing/syncthing/vendor/github.com/syncthing/notify._cgoexpwrap_4ce340c09c06_gostream(0x6b00c30, 0x4, 0x11, 0x6900ef0, 0x4df9000, 0x4df8000)
_cgo_gotypes.go:399 +0x6b
github.com/syncthing/syncthing/vendor/github.com/syncthing/notify._Cfunc_CFRunLoopRu …
```
=> fsevents: Prevent nil deref

watcher_readdcw.go
=> readdcw: debug and skip nil extended completion statuses (fixes #191)

notify.go
I believe it should be _"Calling Watch with empty event list does **not** expand nor shrink watchpoint's event set_".
=> Fix a typo

event_fsevents.go, event_kqueue.go, event_trigger.go, example_fsevents_test.go, watcher_fsevents.go, watcher_fsevents_cgo.go, watcher_fsevents_test.go, watcher_kqueue.go, watcher_kqueue_test.go, watcher_recursive_test.go, watcher_trigger.go, watcher_trigger_test.go
Either cross-compiling or explicit `CGO_ENABLED=0`:
```
GOOS=darwin go build
```
Expected output: builds without an error
Actual output:
```
./watcher_fsevents.go:49:11: undefined: stream
```
This PR addresses this issue by adding a fallback to kqueue on `darwin,!cgo` and enabling fsevents only for `darwin,!kqueue,cgo`.
=> Fix Darwin build without Cgo

event_fen.go, event_stub.go, event_trigger.go, watcher_fen.go, watcher_fen_cgo.go, watcher_fen_test.go, watcher_notimplemented.go, watcher_trigger.go, watcher_trigger_test.go
I added the new illumos build target to the right places analogous to the solaris build tag.
The buildtags inherit from one another so it did build on illumos already but this makes it future proof if the buildtags diverge at some date.
Also, the tests on illumos fail because of missing files?
```text
--- FAIL: TestWatcherFen (0.33s)
testing_test.go:219: testing_test.go:502: missing events for "notify/testdata/506863856/src/github.com/ppknap/link/include/coost/link/detail/stdhelpers" (notify.FileDelete)
testing_test.go:219: testing_test.go:300: w.Watcher.Close()=open notify/testdata/506863856/src/github.com/ppknap/link/include/coost/link/detail: no such file or directory
--- FAIL: TestStopPathNotExists (0.60s)
testing_test.go:219: testing_test.go:300: w.Watcher.Close()=open …
```
=> Add illumos build tags in the right places

notify_test.go, watcher_inotify.go
Steps to reproduce (or just run the test in the PR):
1. Create recursive watch.
2. Create a dir A.
3. Rename the dir to B.
4. Create a file at B/foo
Expected: Event at B/foo
Actual: Event at A/foo
The main fix is in line 100: The path needs to updated too.
I also changed the locking, as both branches of the if require a write-lock, thus acquiring a read-lock first is pointless.
The issue was originally reported in https://github.com/syncthing/syncthing/issues/7076
=> inotify: Fix path when renaming dir in recursive watch

watcher_kqueue.go, watcher_trigger.go
When recursively watching a directory that contains a symlink that points at nothing, it fails with `error while traversing /usr/home/simon/Sync: no such file or directory`. I first wanted to handle that by opening the symlink itself instead of following it, however it turns out that's not supported on BSDs (no `O_SYMLINK`). Ignoring and thus not watching the broken symlink seems more appropriate than failing the entire recursive watch operation.
=> kqueue: Ignore errors due to dangling symlinks

watcher_readdcw.go
We are seeing a few reports of these: `panic: notify: cannot decode internal mask`
This adds the action to the panic message, so we can maybe get an idea of what's wrong there.
=> readdcw: Add action to panic msg

go.mod, node.go, notify_test.go, tree_nonrecursive.go, util.go
I added a test based on the example posted in #200.
The main change is to also pass `Remove` events to `t.rec`, and then unwatch and delete nodes under that path. Thus when it gets created again, new watches will be set up (instead of keeping the old, now invalid watches).
I also fixed some stuff I encountered while debugging and fixing:
- go.mod always changes when running anything like tests. I chose 1.11 because that's when modules started - earlier versions anyway don't care about go.mod.
- Don't re-add already existing created directories - that lead to empty leave nodes (however shouldn't happen any more now that deleted dirs are removed - still better be safe).
- `indexbase` is needlessly complicated. All functions where it is called return an error if the root and name are equal. …
=> Fixes for non-recursive tree when dirs are deleted (fixes #200)

watcher_fsevents.go
In its current implementation, the FSEvents watcher ignores and doesn't forward those 3 events. At the very least if they are triggered, the user should be notified if he subscribed to them.
=> Forward FSEventsUserDropped, FSEventsKernelDropped, FSEventsMustScanSubDirs
